spring:
  application:
    name: Backend


  # DB setting
  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  # .env load
  config:
    import: optional:file:.env[.properties]


  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


